# Generated by Django 3.1.4 on 2020-12-10 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_classe', models.CharField(max_length=40)),
                ('categorie', models.CharField(choices=[('2nd', 'Second'), ('3eme', 'Troisieme'), ('Tle', 'Terminale')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_etablissement', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civil', models.CharField(choices=[('Mr', 'Mister'), ('Mrs', 'Madam'), ('Miss', 'Miss')], max_length=6)),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('date_naissance', models.DateField(verbose_name='date of birth')),
                ('NNI', models.IntegerField()),
                ('frais_inscription', models.IntegerField()),
                ('Annee_s', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=20)),
                ('login', models.CharField(max_length=20)),
                ('mot_de_passe', models.CharField(max_length=20)),
                ('E_mail', models.EmailField(max_length=254)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etablissement.classe')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etablissement.etablissement')),
            ],
        ),
    ]
