# Generated by Django 3.1.4 on 2021-02-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='Email_Tuteur1',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='inscription',
            name='Email_Tuteur2',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='inscription',
            name='Foyer',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='inscription',
            name='N_Eleve',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='inscription',
            name='N_Tel',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='inscription',
            name='Tel_Tuteur1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='inscription',
            name='Tel_Tuteur2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='inscription',
            name='Tuteur1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='inscription',
            name='Tuteur2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='Annee_s',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='E_mail',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='NNI',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='adresse',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='frais_inscription',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='login',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='mot_de_passe',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='nom',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='prenom',
            field=models.CharField(default='', max_length=20),
        ),
    ]
