# Generated by Django 3.1.4 on 2021-02-25 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etablissement', '0002_auto_20210221_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_matiere', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Annee_scolaire', models.CharField(choices=[('annee scolaire', '2020_2021'), ('annee scolaire', '2021_2022'), ('annee scolaire', '2022_2023'), ('annee scolaire', '2023_2024'), ('annee scolaire', '2024_2025')], max_length=40)),
                ('N_Eleve', models.CharField(default='', max_length=20)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etablissement.classe')),
            ],
        ),
    ]
