# Generated by Django 3.1.4 on 2021-02-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissement', '0005_classe_etablissement'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='Adresse',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='Directeur_Etablissement',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='E_mail',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='Telephone',
            field=models.CharField(default='', max_length=40),
        ),
    ]
