# Generated by Django 3.1.4 on 2021-03-02 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etablissement', '0012_remove_etablissement_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comptabilite',
            name='user',
        ),
        migrations.RemoveField(
            model_name='eleve',
            name='user',
        ),
        migrations.RemoveField(
            model_name='emploi_temps',
            name='user',
        ),
        migrations.RemoveField(
            model_name='foyer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='user',
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='user',
        ),
        migrations.RemoveField(
            model_name='professeur',
            name='user',
        ),
    ]
