# Generated by Django 3.1.4 on 2021-03-02 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etablissement', '0013_auto_20210302_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='etablissement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='etablissement.etablissement'),
        ),
    ]
