# Generated by Django 3.1.4 on 2021-03-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissement', '0016_resultat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professeur',
            name='matiere',
        ),
        migrations.AddField(
            model_name='professeur',
            name='matiere',
            field=models.ManyToManyField(to='etablissement.Matiere'),
        ),
    ]
