# Generated by Django 3.1.4 on 2021-03-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissement', '0017_auto_20210303_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professeur',
            name='classe',
        ),
        migrations.AddField(
            model_name='professeur',
            name='classe',
            field=models.ManyToManyField(to='etablissement.Classe'),
        ),
    ]
