# Generated by Django 3.1.4 on 2021-03-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissement', '0018_auto_20210303_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emploi_temps',
            name='time_table',
            field=models.FileField(upload_to='<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.CharField>/emplois_temps/'),
        ),
    ]
