# Generated by Django 3.1.4 on 2021-03-03 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etablissement', '0019_auto_20210303_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emploi_temps',
            name='etablissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etablissement.etablissement'),
        ),
    ]
