# Generated by Django 3.1.4 on 2021-03-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissement', '0021_auto_20210303_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emploi_temps',
            name='time_table',
            field=models.FileField(upload_to='file/'),
        ),
    ]
