# Generated by Django 3.1.4 on 2021-03-03 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etablissement', '0022_auto_20210303_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploi_temps',
            name='user',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emploi_temps',
            name='time_table',
            field=models.FileField(upload_to='time_table/'),
        ),
    ]
